Repository GSA/tbm-scan, pull requests merged in 2019-07, with the labels that each got.

#4 Add list of TBM terms as list file
  TBM_terms_list.py
Labels: enhancement

#6 TST: add CI config and test cases (#5)
  .circleci/config.yml
  requirements.txt
  tbm_scan.py
  tests/fixtures/nightly_file.py
  tests/fixtures/pseudo_xml_to_json_expected.py
  tests/get_nightly_data_test.py
  tests/tbm_scan_test.py
  utils/get_nightly_data.py
Labels: test

#7 DOC: update example command :pencil2: (#5)
  README.md
Labels: documentation

#8 ENH: add filter for TBM terms :sparkles: (#1)
  TBM_terms_list.py
  tbm_scan.py
  tests/get_nightly_data_test.py
  utils/get_nightly_data.py
Labels: enhancement

#9 ENH: add tbm-filter flag to generalize :sparkles: (#1)
  tbm_scan.py
Labels: enhancement

#12 ENH: Add CLI arg for excel output
  .gitignore
  Pipfile
  Pipfile.lock
  requirements.txt
  tbm_scan.py
  tests/writer_test.py
  utils/get_nightly_data.py
  utils/writer.py
Labels: enhancement

#14 ENH: improve TBM filter :sparkles: (#13)
  tests/get_nightly_data_test.py
  utils/get_nightly_data.py
Labels: enhancement

#15 ENH: Format excel to have user-defined columns (#2)
  Pipfile
  Pipfile.lock
  tests/writer_test.py
  utils/writer.py
Labels: enhancement

#16 ENH: Add CLI flag to format excel columns
  README.md
  tbm_scan.py
  tests/writer_test.py
  utils/writer.py
Labels: enhancement
